#tasks/centos.yml
---
- name: Install MariaDB
  yum: name={{item}} update_cache=yes state=latest
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python

#Для каждого семейства ОС используется свой шаблон для my.cnf, т.к. сокеты и pid-файлы в MySQL и MariaDB имеют разное название

# Хорошо, только убери точку в начале имени файла. И, в целях безопасности, не записывай туда логины и пароли.
# Логины и пароли должны находиться в домашнем каталоге пользователя, в файле с именем .my.cnf,
# с правами, позволяющими только одному этому пользователю читать этот файл.
- name: Copy .my.cnf file with root password credentials
  template:
    src: centos.my.cnf.j2
    dest: /etc/.my.cnf

- name: Start MariaDB
  service: name=mariadb state=started enabled=true

- name: Configure database
  include: dbconfigure.yml
