#tasks/main.yml
---
# Здесь то же, что и в роли apache
- name: Ensure MySQL is installed
  shell: dpkg-query -W mysql-server
  register: mysql_installed
  failed_when: mysql_installed.rc > 1
  when: ansible_os_family == "Debian"

- name: Ensure MariaDB is installed
  shell: yum list installed mariadb warn=no
  register: mariadb_installed
  failed_when: mariadb_installed.rc > 1
  when: ansible_os_family == "RedHat"

- name: Run CentOS-specific tasks
  include: centos.yml
  when: ansible_os_family == "RedHat" and mariadb_installed.rc == 1

- name: Run Ubuntu-specific tasks
  include: ubuntu.yml
  when: ansible_os_family == "Debian" and mysql_installed.rc == 1